import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Providers } from '@/components/providers/Providers';
import { RootNavbar } from '@/components/layout/RootNavbar';
import { Toaster } from 'sonner';
import { ROUTES } from '@/lib/constants/routes';
import { getUser, isAdminByEmail } from '@/lib/helpers/auth-helper';
import { getUserDisplayName } from '@/lib/utils/auth-utils';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  const isAdmin = user?.email ? await isAdminByEmail(user.email) : false;
  const initialUser = {
    isAuthenticated: !!user,
    displayName: getUserDisplayName(user),
    avatarHref: isAdmin ? ROUTES.ADMIN_DASHBOARD : ROUTES.MEMBERSHIP_DASHBOARD,
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <RootNavbar initialUser={initialUser} />
          {children}
          <Toaster
            position="top-center"
            richColors
            toastOptions={{
              className:
                'text-destructive border-destructive',
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
